WIFI_SSID = 'YOUR_WIFI_SSID' # CHANGE THIS
WIFI_PASS = 'YOUR_WIFI_PASSWORD' # CHANGE THIS

AIO_HUMIDITY_FEED = "YOUR_AIO_ID/feeds/humidity" # CHANGE THIS
AIO_TEMPERATURE_FEED = "YOUR_AIO_ID/feeds/temperature" # CHANGE THIS
#AIO_IR_FEED = "YOUR_AIO_ID/feeds/ir"
AIO_KNOCK_FEED = "YOUR_AIO_ID/feeds/knock" # CHANGE THIS
AIO_LIGHT_FEED = "YOUR_AIO_ID/feeds/light" # CHANGE THIS
AIO_ROTARY_FEED = "YOUR_AIO_ID/feeds/rotary" # CHANGE THIS
#AIO_VIBRATE_FEED = "YOUR_AIO_ID/feeds/vibrate"

AIO_CLIENT_ID = "RaspberryPicoW"
AIO_SERVER = "io.adafruit.com"
AIO_PORT = 1883
AIO_USER = "YOUR_AIO_ID" # CHANGE THIS
AIO_KEY = "YOUR_AIO_KEY" # CHANGE THIS
